apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-inspector
spec:
  replicas: 3
  selector:
    app: flask-inspector
  template:
    metadata:
      name: flask-inspector
      labels:
        app: flask-inspector
    spec:
      containers:
      - name: flask_inspector
        image: fvcdaniel/flask_inspector:latest
        ports:
        - containerPort: 5000
          protocol: TCP
